version: '3.7'

services:
  devsu:
    image: devsu:0.1

    build:
      context: ./
      dockerfile: Dockerfile

    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.2'
          memory: 96M
        reservations:
          cpus: '0.1'
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 10s

    ports:
      - "8000:8000"

    networks:
      lb_proxy:
        aliases:
          - devsu

    healthcheck:
      test: curl --fail http://localhost:8000/api/ || exit 1
      interval: 20s
      start_period: 60s
      timeout: 5s
      retries: 3

networks:
  lb_proxy:
    external: true
