apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu
data:
  database_name: "/data/db.sqlite3"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devsu
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: devsu-demo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devsu-demo
      name: devsu-demo
    spec:
      containers:
        - image: erromu/devsu-demo:0.1
          name: devsu-demo
          livenessProbe:
            exec:
              command:
              - curl --fail http://localhost:8000/api/
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 1
          ports:
            - containerPort: 8000
              protocol: TCP
              name: devsu-http-web
          resources:
            limits:
              cpu: 300m
              memory: "128M"
            requests:
              cpu: 100m
              memory: "64M"
          volumeMounts:
          - mountPath: /data
            name: volume
          env:
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: devsu
                  key: database_name
      #restartPolicy: Always
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: devsu

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devsu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devsu
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: devsu
spec:
  selector:
    app: devsu-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: devsu-http-web

