name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      env:
        DOCKER_USER: ${{ env.DOCKER_TOKEN }}
        DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
      run: |
        echo $DOCKER_USER
        docker build . --file Dockerfile --tag erromu/devsu-demo:0.1
        docker login registry-1.docker.io -u $DOCKER_USER -p $DOCKER_TOKEN
        docker push erromu/devsu-demo:0.1
