name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: |
          docker build . --file Dockerfile --tag erromu/devsu-demo:$(date +%s)
          docker login registry-1.docker.io -u $DOCKER_USER -p $DOCKER_TOKEN
          docker push erromu/devsu-demo:$(date +%s)
